
export let FONTS = [
  { value: "Arial, Helvetica, sans-serif", name: "Arial"},
  { value: "Arial Black, Gadget, sans-serif", name: "Arial Black"},
  { value: "Brush Script MT, sans-serif", name: "Brush Script MT"},
  { value: "Comic Sans MS, cursive, sans-serif", name: "Comic Sans MS"},
  { value: "Courier New, Courier, monospace", name: "Courier New"},
  { value: "Georgia, serif", name: "Georgia"},
  { value: "Helvetica, sans-serif", name: "Helvetica"},
  { value: "Impact, Charcoal, sans-serif", name: "Impact"},
  { value: "Lucida Sans Unicode, Lucida Grande, sans-serif", name: "Lucida Sans Unicode"},
  { value: "Tahoma, Geneva, sans-serif", name: "Tahoma"},
  { value: "Times New Roman, Times, serif", name: "Times New Roman"},
  { value: "Trebuchet MS, Helvetica, sans-serif", name: "Trebuchet MS"},
  { value: "Verdana, Geneva, sans-serif", name: "Verdana"},
]

export let LINE_TYPES = [
  { value: 'solid', name: 'solid' },
  { value: 'dashed', name: 'dashed' },
  { value: 'dotted', name: 'dotted' },
]

export let ANIMATIONEASING=[{name:"linear"},
  {name:"quadraticLn",value:"quadraticLn"},
  {name:"quadraticOut",value:"quadraticOut"},
  {name:"quadraticInOut",value:"quadraticInOut"},
  {name:"cubicIn",value:"cubicIn"},
  {name:"cubicOut",value:"cubicOut"},
  {name:"cubicInOut",value:"cubicInOut"},
  {name:"quarticIn",value:"quarticIn"},
  {name:"quarticOut",value:"quarticOut"},
  {name:"quarticInOut",value:"quarticInOut"},
  {name:"quinticIn",value:"quinticIn"},
  {name:"quinticOut",value:"quinticOut"},
  {name:"quinticInOut",value:"quinticInOut"},
  {name:"sinusoidalIn",value:"sinusoidalIn"},
  {name:"sinusoidalOut",value:"sinusoidalOut"},
  {name:"sinusoidalInOut",value:"sinusoidalInOut"},
  {name:"exponentialIn",value:"exponentialIn"},
  {name:"exponentialOut",value:"exponentialOut"},
  {name:"exponentialInOut",value:"exponentialInOut"},
  {name:"circularIn",value:"circularIn"},
  {name:"circularOut",value:"circularOut"},
  {name:"circularInOut",value:"circularInOut"},
  {name:"elasticIn",value:"elasticIn"},
  {name:"elasticOut",value:"elasticOut"},
  {name:"elasticInOut",value:"elasticInOut"},
  {name:"backIn",value:"backIn"},
  {name:"backOut",value:"backOut"},
  {name:"backInOut",value:"backInOut"},
  {name:"bounceIn",value:"bounceIn"},
  {name:"bounceOut",value:"bounceOut"},
  {name:"bounceInOut",value:"bounceInOut"},
]
export let BLENDMODE= ['source-over',
  'source-in',
  'source-out',
  'source-atop',
  'destination-over',
  'destination-in',
  'destination-out',
  'destination-atop',
  'lighter',
  'copy',
  'xor',
  'multiply',
  'screen',
  'overlay',
  'darken',
  'lighten',
  'color-dodge',
  'color-burn',
  'hard-light',
  'soft-light',
  'difference',
  'exclusion',
  'hue',
  'saturation',
  'color',
  'luminosity',
]