
export let TEXT_STYLE = {
  color: '#333',
  fontStyle: 'normal',
  fontWeight: 'normal',
  fontFamily: 'sans-serif',
  fontSize: 12,
  align: 'left',
  verticalAlign: 'top',
  lineHeight: 24,
  backgroundColor: 'transparent',
  borderColor: 'transparent',
  borderWidth: 0,
  borderType: 'solid',
  // borderDashOffset: 0,
  // borderRadius: 0,
  padding: [0, 0, 0, 0]
  // shadowColor: 'transparent',
  // shadowBlur: 0,
  // shadowOffsetX: 0,
  // shadowOffsetY: 0,
  // width: 'auto',
  // height: 'auto',
  // textBorderColor: 'auto',
  // textBorderWidth: 0,
  // textBorderType: 'solid',
  // textBorderDashOffset: 0,
  // textShadowColor: 'transparent',
  // textShadowBlur: 0,
  // textShadowOffsetX: 0,
  // textShadowOffsetY: 0,
  // overflow: 'none',
  // ellipsis: '...',
}

export let LINE_STYLE = {
  color: '#333',
  width: 1,
  type: 'solid',
  dashOffset: 0,
  cap: 'butt',
  join: 'bevel',
  miterLimit: 10,
  shadowBlur: 'auto',
  shadowColor: 'auto',
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  opacity: 1
}
